import json
import logging
from datetime import datetime, timezone
from backend.src.models.export import ExportPlan, ExportRequest

logger = logging.getLogger(__name__)


class ExportService:
    def generate_json(self, request: ExportRequest) -> str:
        plan = ExportPlan(
            trip_context=request.trip_context,
            itinerary=request.itinerary,
            generated_at=datetime.now(timezone.utc).isoformat(),
        )
        return plan.model_dump_json(indent=2)

    def generate_pdf(self, request: ExportRequest) -> bytes:
        html = _build_html(request)
        return self._render_pdf(html)

    def _render_pdf(self, html: str) -> bytes:
        try:
            from weasyprint import HTML  # lazy import — fails gracefully on Windows without GTK
            return HTML(string=html).write_pdf()
        except OSError as e:
            raise RuntimeError(
                f"WeasyPrint requires GTK system libraries (not available on Windows). "
                f"Deploy on Linux for PDF generation. Original error: {e}"
            ) from e


def _build_html(request: ExportRequest) -> str:
    ctx = request.trip_context
    legs_summary = ""
    for leg in ctx.legs:
        flight_info = ""
        if leg.selected_flight:
            f = leg.selected_flight
            seg = f.segments[0]
            flight_info = f"<p>✈ {seg.departure_airport} → {seg.arrival_airport} · {f.price} {f.currency}</p>"
        stays = "".join(
            f"<p>🏨 {s.hotel.name} ({s.check_in} – {s.check_out})</p>"
            for s in leg.hotel_stays
        )
        legs_summary += (
            f"<div class='leg'>"
            f"<h3>Leg {leg.leg_number}: {leg.origin} → {leg.destination}</h3>"
            f"{flight_info}{stays}"
            f"</div>"
        )

    days_html = ""
    for day in request.itinerary:
        items_html = "".join(
            "<li>"
            + item.name
            + f" — {item.address}"
            + (f" ({item.duration_mins} min)" if item.duration_mins else "")
            + (
                f" <span class='distance'>{item.travel_time_to_next_mins} min · {item.distance_to_next_km} km →</span>"
                if item.distance_to_next_km
                else ""
            )
            + "</li>"
            for item in day.items
        )
        days_html += (
            f"<div class='day'>"
            f"<h3>Day {day.day_number} — {day.date} · {day.city}</h3>"
            f"<p class='narrative'>{day.narrative}</p>"
            f"<ul>{items_html}</ul>"
            f"</div>"
        )

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8'>
<style>
  body {{ font-family: Georgia, serif; max-width: 800px; margin: 40px auto; color: #333; }}
  h1 {{ color: #1a1a2e; }}
  h2 {{ color: #16213e; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; }}
  h3 {{ color: #0f3460; }}
  .leg {{ background: #f8f9fa; padding: 12px; border-radius: 4px; margin: 8px 0; }}
  .day {{ margin: 24px 0; }}
  .narrative {{ font-style: italic; color: #555; }}
  .distance {{ color: #888; font-size: 0.85em; }}
  ul {{ list-style: none; padding: 0; }}
  li {{ padding: 4px 0; border-bottom: 1px solid #eee; }}
</style>
</head>
<body>
<h1>Trip Plan</h1>
<p>{ctx.adults} adults{f' + {ctx.children} children' if ctx.children else ''} · Departing from {ctx.home_origin}</p>
<h2>Flight &amp; Hotel Summary</h2>
{legs_summary}
<h2>Itinerary</h2>
{days_html}
<p style='color:#aaa;font-size:0.8em;margin-top:40px;'>Generated by Travel Agent Assistant</p>
</body>
</html>"""
