"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useTripContext } from "@/context/TripContext";
import { ItinerarySummary } from "@/components/export/ItinerarySummary";
import { ExportButtons } from "@/components/export/ExportButtons";
import { Button } from "@/components/ui/Button";
import { api } from "@/services/api";
import type { TransportSegment } from "@/types/trip";
import { ArrowLeft, RefreshCw, Loader2 } from "lucide-react";

export default function ExportPage() {
  const router = useRouter();
  const { state, dispatch } = useTripContext();
  const { tripContext, itinerary } = state;
  const [generating, setGenerating] = useState(false);
  const [generateError, setGenerateError] = useState("");
  const autoGeneratedRef = useRef(false);

  const hasDays = tripContext.legs.some((l) => l.days.length > 0);

  useEffect(() => {
    if (itinerary.length > 0 || !hasDays || autoGeneratedRef.current) return;
    autoGeneratedRef.current = true;

    setGenerating(true);
    setGenerateError("");

    const allDays = tripContext.legs.flatMap((l) => l.days);

    api.generateItinerary({
      ...tripContext,
      legs: tripContext.legs.map((leg) => ({ ...leg, days: leg.days })),
    })
      .then((narratives) => {
        const itineraryDays = allDays.map((day) => ({
          day_number: day.day_number,
          date: day.date,
          city: day.city,
          narrative: narratives[`day_${day.day_number}`] ?? "",
          items: day.items,
        }));
        dispatch({ type: "SET_ITINERARY", payload: itineraryDays });
      })
      .catch((e) => {
        console.error("Itinerary generation failed:", e);
        setGenerateError("Failed to generate itinerary narrative. You can still export your trip.");
      })
      .finally(() => setGenerating(false));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (tripContext.legs.length === 0) {
    return (
      <div className="max-w-3xl mx-auto text-center py-16">
        <p className="font-body text-ink-muted">
          Your session was reset.{" "}
          <Link href="/trips" className="underline text-teal hover:text-teal-hover">
            Visit your trips page
          </Link>{" "}
          to restore a saved trip.
        </p>
      </div>
    );
  }

  // Build transport segments from legs
  const transportSegments: TransportSegment[] = tripContext.legs.map((leg) => ({
    leg_number: leg.leg_number,
    mode: leg.transport_mode ?? "flight",
    origin: leg.origin,
    destination: leg.destination,
    departure_date: leg.departure_date,
    booking_ref: leg.selected_flight
      ? `${leg.selected_flight.segments[0]?.carrier_code}${leg.selected_flight.segments[0]?.flight_number}`
      : undefined,
    notes:
      leg.transport_mode === "ferry"
        ? "Book via ferry operator website"
        : leg.transport_mode === "train"
        ? "Book via Trainline, Eurail, or national rail"
        : leg.transport_mode === "car"
        ? "Self-drive or hire car"
        : undefined,
  }));

  const exportRequest = {
    trip_context: tripContext,
    itinerary: itinerary.length > 0 ? itinerary : [],
    transport_segments: transportSegments,
  };

  return (
    <div className="max-w-2xl mx-auto py-10 px-4">
      {/* Header */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between mb-8">
        <div>
          <p className="text-[10px] font-semibold uppercase tracking-[2.5px] mb-1 font-body text-teal">
            Step 5 of 5
          </p>
          <h1 className="font-display text-[34px] font-medium text-ink">
            Your Trip Summary
          </h1>
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant="primary"
            size="sm"
            onClick={() => router.push("/")}
            icon={<RefreshCw size={14} />}
          >
            Plan another trip
          </Button>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => router.push("/itinerary")}
            icon={<ArrowLeft size={14} />}
          >
            Edit Itinerary
          </Button>
        </div>
      </div>

      {/* Generating banner */}
      {generating && (
        <div
          className="rounded-xl px-4 py-3 mb-6 flex items-center gap-3 font-body text-sm"
          style={{
            background: "var(--glass-2)",
            border: "1px solid var(--glass-border-2)",
          }}
        >
          <Loader2 size={15} className="animate-spin shrink-0 text-teal" />
          <span className="text-ink-muted">Generating your itinerary narrative…</span>
        </div>
      )}

      {generateError && (
        <div
          className="rounded-xl px-4 py-3 mb-6 font-body text-sm"
          style={{
            color: "var(--accent)",
            background: "rgba(224,122,95,0.10)",
            border: "1px solid rgba(224,122,95,0.25)",
          }}
        >
          {generateError}
        </div>
      )}

      <div className="space-y-8">
        {/* Export buttons at top */}
        <div className="rounded-xl p-5 bg-surface border border-border shadow-sm">
          <h2 className="font-semibold mb-3 font-body text-sm text-ink">Export Your Plan</h2>
          <ExportButtons exportRequest={exportRequest} disabled={generating} />
        </div>

        <ItinerarySummary tripContext={tripContext} itinerary={itinerary} />

        {/* Export buttons at bottom */}
        <div
          className="rounded-xl p-5"
          style={{
            background: "var(--glass-2)",
            border: "1px solid var(--glass-border-2)",
            backdropFilter: "blur(12px)",
            boxShadow: "0 4px 24px rgba(0,0,0,0.3)",
          }}
        >
          <ExportButtons exportRequest={exportRequest} disabled={generating} />
        </div>

        <div className="pb-6" />
      </div>
    </div>
  );
}
